2398-he-give-cmd
NationsGlory/HawkEye pull request #4
Opened 2024-02-03 18:12 UTC by TheKing4012

2024-02-03 18:15 UTC, TheKing4012 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter la possibilité de se give une transaction Hawkeye](https://trello.com/c/hTF6p1T4/2398-ajouter-la-possibilit%C3%A9-de-se-give-une-transaction-hawkeye)

2024-02-11 08:33 UTC, iBalix requested changes

2024-02-11 08:33 UTC, iBalix commented on lib/src/main/java/uk/co/oliwali/HawkEye/commands/GiveCommand.java
> +            /*
Commentaire à retirer

2024-02-11 11:01 UTC, TheKing4012 commented on lib/src/main/java/uk/co/oliwali/HawkEye/commands/GiveCommand.java
> +            /*
Done ✅

2024-03-08 13:33 UTC, merged